### ISSUE TITLE
There is another similar project you may wish to check out.

### ISSUE THREAD

**Issue by blockchainunchained** [strawberrydarling/eth2-validator-playbook#2]
Hello,

Not sure if this is being actively maintained or not, it doesn't look like it. I just wanted to let you know that this package inspired me to add Lighthouse support to another Ethereum 2.0 Validator Ansible Role.

You can find it here: https://github.com/MaximilianMeister/ethereum-validator

Lighthouse support has not been merged yet but it is coming soon.

We would love to have your assistance over on that project if your still looking to work on this or something similar

Cheers,

BU

**Comment by strawdar** [comment]
Hey, thanks for reaching out! As you've probably seen the amount of time I can commit to a larger project isn't very reliable right now, which is why I sporadically solo maintain my configuration here.

The lack of updates is because everything has been running smoothly, but soon I'll be working on a branch for prater testnet to prep for the merge.
